version: "3"
services:
  portainer:
    image: portainer/portainer-ce:latest
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  caddy:
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
    restart: unless-stopped
volumes:
  portainer_data:
  caddy_data:
  